FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=kaapav
ENV N8N_BASIC_AUTH_PASSWORD=rocket@064
ENV N8N_HOST=0.0.0.0
ENV WEBHOOK_URL=https://kaapav-wa-bot.onrender.com
ENV DB_SQLITE_VACUUM_ON_STARTUP=true

CMD ["n8n"]
