services:
  - type: web
    name: kaapav-n8n-bot
    env: docker
    plan: free
    region: singapore
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 1
    autoDeploy: true
